[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
diesel = { version = "2.2.0", features = ["postgres"] }
dotenvy = "0.15"

[[bin]]
name = "backend"
path = "src/main.rs"
